-- Creates the puzzles table with the full product schema.
-- (The table previously existed only via the dashboard, not via migrations.)
-- board_layout stores hex grid state in axial (q, r) coordinates — honeycomb-grid default.
-- Schema: { tiles: [{q,r,terrain,number}], settlements: [{q,r,vertex,player,type}],
--           roads: [{q,r,edge,player}], robber: {q,r}, ports: [{q,r,type,edge}] }

CREATE TABLE IF NOT EXISTS public.puzzles (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    description text,
    difficulty text,
    image_url text,
    solved_amount bigint DEFAULT 0,
    explanation text,
    creator_user uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
    choices text[],
    correct_choice smallint DEFAULT 0,
    board_layout jsonb,
    target_points smallint,
    move_limit smallint
);

ALTER TABLE public.puzzles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view puzzles"
    ON public.puzzles FOR SELECT TO public USING (true);

CREATE POLICY "Authenticated users can create puzzles"
    ON public.puzzles FOR INSERT TO authenticated WITH CHECK (creator_user = auth.uid());

CREATE POLICY "Creators can update own puzzles"
    ON public.puzzles FOR UPDATE TO authenticated USING (creator_user = auth.uid());

CREATE POLICY "Creators can delete own puzzles"
    ON public.puzzles FOR DELETE TO authenticated USING (creator_user = auth.uid());
