-- Per-user puzzle attempt history. One row per (user, puzzle) pair.
CREATE TABLE public.user_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    puzzle_id bigint NOT NULL REFERENCES public.puzzles(id) ON DELETE CASCADE,
    completed boolean DEFAULT false NOT NULL,
    attempts smallint DEFAULT 0 NOT NULL,
    solved_at timestamp with time zone,
    UNIQUE (user_id, puzzle_id)
);

ALTER TABLE public.user_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own progress"
    ON public.user_progress FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own progress"
    ON public.user_progress FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own progress"
    ON public.user_progress FOR UPDATE TO authenticated USING (auth.uid() = user_id);
