-- Maps one calendar date to one featured puzzle.
-- Populated manually or via a scheduled Edge Function.
CREATE TABLE public.daily_challenge (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    challenge_date date NOT NULL UNIQUE,
    puzzle_id bigint NOT NULL REFERENCES public.puzzles(id) ON DELETE RESTRICT
);

ALTER TABLE public.daily_challenge ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view daily challenges"
    ON public.daily_challenge FOR SELECT TO public USING (true);

-- Only service_role (server-side / Edge Functions) can write to this table
CREATE POLICY "Service role manages daily challenges"
    ON public.daily_challenge FOR ALL TO service_role USING (true);
